---
title: "Simulate CLPM and fit with lavaan"
author: "Kristoffer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = "~/gametime-longitudinal")
library(tidyverse)
library(lavaan)
```


# Simulate data from CLPM
```{r}
# see file for params
source("Models/RI-CLPM/simulate-RICLPM-data.R")
# CLPM becase random intercepts = 0
params <- list(
    n = 10000,
    # beta = autoregressive params
    beta_2x = 0.66,
    beta_2y = 0.55,
    beta_3x = 0.40,
    beta_3y = 0.33,
    # gamma = cross-lagged effects
    gamma_2x = 0.22,
    gamma_2y = 0.33,
    gamma_3x = 0.44,
    gamma_3y = 0.55,
    x_mean = 2,
    y_mean = 4,
    ## covariances
    sd_wx1 = 1,
    sd_wy1 = 1,
    cor_wx1_wy1 = 0.5,
    sd_wx2 = 1.7,
    sd_wy2 = 1.33,
    cor_wx2_wy2 = 0.6,
    sd_wx3 = 1.33,
    sd_wy3 = 1.44,
    cor_wx3_wy3 = 0.44,
    sd_x_RE = 0,
    sd_y_RE = 0,
    cor_xy_intercepts = 0
)
d <- do.call(sim_RICLPM_data, params)

head(d)
```

```{r}
CLPM <- '
  # Estimate the lagged effects between the observed variables.
  x2 + y2 ~ x1 + y1
  x3 + y3 ~ x2 + y2

  # Estimate the covariance between the observed variables at the first wave. 
  x1 ~~ y1 # Covariance
  
  # Estimate the covariances between the residuals of the observed variables.
  x2 ~~ y2
  x3 ~~ y3
  
  # Estimate the (residual) variance of the observed variables.
  x1 ~~ x1 # Variances
  y1 ~~ y1 
  x2 ~~ x2 # Residual variances
  y2 ~~ y2 
  x3 ~~ x3 
  y3 ~~ y3 
'
fit_CLPM <- lavaan(CLPM, data = d, meanstructure = TRUE, int.ov.free = TRUE) 
summary(fit_CLPM, standardized = FALSE)
```

## Compare coefs to thetas
```{r}
create_comparison_df <- function(fit, params) {
    coefs <- coef(fit)
    res <- data.frame(
        term = names(coefs),
        est = coefs,
        theta = with(
            params,
            c(
                beta_2x,
                gamma_2x,
                gamma_2y,
                beta_2y,
                beta_3x,
                gamma_3x,
                gamma_3y,
                beta_3y,
                sd_wx1 * sd_wy1 * cor_wx1_wy1,
                sd_wx2 * sd_wy2 * cor_wx2_wy2,
                sd_wx3 * sd_wy3 * cor_wx3_wy3,
                sd_wx1^2,
                sd_wy1^2,
                sd_wx2^2,
                sd_wy2^2,
                sd_wx3^2,
                sd_wy3^2,
                rep(NA, 6) # ignore means
            )
        ),
        row.names = NULL
    )
    res
}
res <- create_comparison_df(fit_CLPM, params)
knitr::kable(res, digits = 2)
```

Plot the comparison
```{r}
coef_names <- names(coef(fit_CLPM))
ggplot(res, aes(y = factor(term, levels = coef_names))) +
    geom_point(aes(x = est, color = "est")) +
    geom_point(aes(x = theta, color = "theta")) +
    labs(
        y = "Terms", 
        x = "Value",
        title = "CLPM fit to CLPM data"
    )
```

## Fit CLPM to RICLPM data
```{r}
# Update with arbitrary params for random intercepts
params$sd_x_RE <- 1.2
params$sd_y_RE = 1.44
params$cor_xy_intercepts = 0.33
# Fake data
d2 <- do.call(sim_RICLPM_data, params)
# Fit CLPM
fit_CLPM2 <- lavaan(CLPM, data = d2, meanstructure = TRUE, int.ov.free = TRUE) 
res <- create_comparison_df(fit_CLPM2, params)
# Plot comparison
ggplot(res, aes(y = factor(term, levels = coef_names))) +
    geom_point(aes(x = est, color = "est")) +
    geom_point(aes(x = theta, color = "theta")) +
    labs(
        y = "Terms", 
        x = "Value",
        title = "CLPM fit to RI-CLPM data"
    )
```


## Notes
* DGP looks correct
* Model highly unrealistic
    - no measurement error
    - clearly biased when random intercept added
    - i.e., zero confounding, not even stable traits

