---
title: "Simulate RICLPM and fit with lavaan"
author: "Kristoffer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = "~/gametime-longitudinal")
library(tidyverse)
library(lavaan)
```


# Simulate data from RICLPM
```{r}
#set.seed(1337)
source("Models/RI-CLPM/simulate-RICLPM-data.R")
params <- list(
    n = 10000,
    # beta = autoregressive params
    beta_2x = 0.66,
    beta_2y = 0.55,
    beta_3x = 0.40,
    beta_3y = 0.33,
    # gamma = cross-lagged effects
    gamma_2x = 0.22,
    gamma_2y = 0.33,
    gamma_3x = 0.44,
    gamma_3y = 0.55,
    x_mean = 2,
    y_mean = 4,
    ## covariances
    sd_wx1 = 1,
    sd_wy1 = 1,
    cor_wx1_wy1 = 0.5,
    sd_wx2 = 1.7,
    sd_wy2 = 1.33,
    cor_wx2_wy2 = 0.6,
    sd_wx3 = 1.33,
    sd_wy3 = 1.44,
    cor_wx3_wy3 = 0.44,
    sd_x_RE = 1.2,
    sd_y_RE = 1.44,
    cor_xy_intercepts = 0.33
)
d <- do.call(sim_RICLPM_data, params)
head(d)
```

```{r}
riclpm <- '
  # Create between components (random intercepts)
  RIx =~ 1*x1 + 1*x2 + 1*x3
  RIy =~ 1*y1 + 1*y2 + 1*y3

  # Create within-person centered variables
  wx1 =~ 1*x1
  wx2 =~ 1*x2
  wx3 =~ 1*x3
  wy1 =~ 1*y1
  wy2 =~ 1*y2
  wy3 =~ 1*y3

  # Estimate the lagged effects between the within-person centered variables.
  wx2 + wy2 ~ wx1 + wy1
  wx3 + wy3 ~ wx2 + wy2

  # Estimate the covariance between the within-person centered
  # variables at the first wave.
  wx1 ~~ wy1 # Covariance

  # Estimate the covariances between the residuals of the
  # within-person centered variables (the innovations).
  wx2 ~~ wy2
  wx3 ~~ wy3

  # Estimate the variance and covariance of the random intercepts.
  RIx ~~ RIx
  RIy ~~ RIy
  RIx ~~ RIy

  # Estimate the (residual) variance of the within-person centered variables.
  wx1 ~~ wx1 # Variances
  wy1 ~~ wy1
  wx2 ~~ wx2 # Residual variances
  wy2 ~~ wy2
  wx3 ~~ wx3
  wy3 ~~ wy3
'
fit_RICLPM <- lavaan(
    riclpm, 
    data = d, 
    meanstructure = TRUE, 
    int.ov.free = TRUE
) 
summary(fit_RICLPM, standardized = FALSE)
```

## Compare coefs to thetas
```{r}
coefs <- coef(fit_RICLPM)
res <- data.frame(
    term = names(coefs),
    est = coefs,
    theta = with(
        params,
            c(
                beta_2x,
                gamma_2x,
                gamma_2y,
                beta_2y,
                beta_3x,
                gamma_3x,
                gamma_3y,
                beta_3y,
                sd_wx1 * sd_wy1 * cor_wx1_wy1,
                sd_wx2 * sd_wy2 * cor_wx2_wy2,
                sd_wx3 * sd_wy3 * cor_wx3_wy3,
                sd_x_RE^2,
                sd_y_RE^2,
                sd_x_RE * sd_y_RE * cor_xy_intercepts,
                sd_wx1^2,
                sd_wy1^2,
                sd_wx2^2,
                sd_wy2^2,
                sd_wx3^2,
                sd_wy3^2,
                rep(NA, 6) # ignore means
            )
    ),
    row.names = NULL
)

knitr::kable(res, digits = 2)
```

Plot the comparison
```{r}
ggplot(res, aes(y = factor(term, levels = c(names(coefs))))) + 
    geom_point(aes(x = est, color = "est")) +
    geom_point(aes(x = theta, color = "theta")) +
    labs(
        y = "Terms",
        x = "Value",
        title = "RI-CLPM fit to RI-CLPM data"
    )
```

## Notes
* DGP looks correct
* Model slightly more realistic compared to CLPM
    - still no measurement error
    - will only deal with stable trait confounding

